"""DDL 元数据功能的公开类型契约。"""

from data_agent.ddl_metadata.models.base import ContractModel
from data_agent.ddl_metadata.models.jobs import (
    AnswerRequest,
    DDLJobAccepted,
    DDLJobRequest,
    JobError,
    JobRecord,
    JobResult,
    JobStatus,
)
from data_agent.ddl_metadata.models.memory import (
    MEMORY_CONTENT_ADAPTER,
    MemoryCandidate,
    MemoryContent,
    MemoryCorrectionRequest,
    MemoryCorrectionResponse,
    MemoryDetail,
    MemoryKind,
    MemoryListItem,
    MemoryPage,
    MemoryPatchRequest,
    MemoryPayload,
    MemoryRelation,
    MemoryRelationType,
    MemoryRowStatus,
    MetricDefinitionContent,
    MetricQuestionContent,
    PayloadRebuildResult,
    SemanticDecisionContent,
    UserAnswerContent,
)
from data_agent.ddl_metadata.models.physical import (
    PhysicalColumn,
    PhysicalSchema,
    PhysicalTable,
)
from data_agent.ddl_metadata.models.semantic import (
    ColumnRole,
    MetricAnswer,
    MetricMetadata,
    MetricOutput,
    MetricQuestion,
    MetricQuestionSet,
    SemanticColumn,
    SemanticMetadata,
    SemanticTable,
    TableRole,
    ValidationIssue,
)

__all__ = [
    "MEMORY_CONTENT_ADAPTER",
    "AnswerRequest",
    "ColumnRole",
    "ContractModel",
    "DDLJobAccepted",
    "DDLJobRequest",
    "JobError",
    "JobRecord",
    "JobResult",
    "JobStatus",
    "MemoryCandidate",
    "MemoryContent",
    "MemoryCorrectionRequest",
    "MemoryCorrectionResponse",
    "MemoryDetail",
    "MemoryKind",
    "MemoryListItem",
    "MemoryPage",
    "MemoryPatchRequest",
    "MemoryPayload",
    "MemoryRelation",
    "MemoryRelationType",
    "MemoryRowStatus",
    "MetricAnswer",
    "MetricDefinitionContent",
    "MetricMetadata",
    "MetricOutput",
    "MetricQuestion",
    "MetricQuestionContent",
    "MetricQuestionSet",
    "PayloadRebuildResult",
    "PhysicalColumn",
    "PhysicalSchema",
    "PhysicalTable",
    "SemanticColumn",
    "SemanticDecisionContent",
    "SemanticMetadata",
    "SemanticTable",
    "TableRole",
    "UserAnswerContent",
    "ValidationIssue",
]
